# Dependencies
markdown:            kramdown
highlighter:         rouge

# Gems (for Jekyll 3.0)
gems: [jekyll-paginate]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Naringu
tagline:             'A Hacker like jekyll theme'
description:         'oonlab is crafted with <3 by ariestiyansyah.'
baseurl: "/pretendB/" # the subpath of your site, e.g. /blog
url: "https://mengyangxu.github.io" # the base hostname & protocol for your site
paginate:            7

# About/contact
author:
  name:              Rizky Ariestiyansyah

  email:             ariestiyansyah.rizky@gmail.com

# Custom vars
version:             2.0

# Social Media
github:				http://github.com/ariestiyansyah
twitter:			http://twitter.com/ariestiyansyah
disqus:             testnaringu

# Theme Author (Please don't edit this line cause of MIT LICENSE rules)
theme:
  creator:			Rizky Ariestiyansyah
  codename:			Naringu
  link:             https://github.com/ariestiyansyah/naringu
